### ISSUE TITLE
Allow SecretBox.easy to also accept user Uint8List key instead of only generated ones

### ISSUE THREAD

**Issue by gabrielpacheco23** [Skycoder42/libsodium_dart_bindings#1]
The problem is that I can't pass my secret key array (`Uint8List` type) inside the function because it only accepts `SecureKey` instances and `SecureKey` objects are only created by this library key generation.

**Comment by Skycoder42** [comment]
Hi @gabrielpacheco23 - thanks for trying out the library in it's early stages.

This is actually something I had on my list for quite a while. I just pushed a commit that adds a `Sodium.secureCopy` method, which allows you to create a `SecureKey` by copying a `Uint8List`.

However, I am still unsure about how the API should work with the keys. In other languages, I would just overload the methods to accept both, a SecureKey and a Uint8Array, but I can't do that in dart. So, I though about the following alternative approaches. I would like to hear your opinion, if you have one:

1. Keep the API as is
2. Add an additional `Uint8List plainKey` parameter and make the normal key optional - this API-consumers can decide, which type of key the want to add - however, at the cost of runtime checks, if a key was actually provided.
3. Add factory constructors to `SecureKey`, to make it easier to use, as well as a `SecureKey.unsafe` constructor, which just wraps a `Uint8List` for easy consumption.

**Comment by gabrielpacheco23** [comment]
Thanks for the quick reply! Before this answer I had used a workaround with an extension method in the SecretBox class. That's how I made it: 
```dart
extension KeyExt on SecretBox {
  SecureKey keyFromBytes(Uint8List rawBytes, DynamicLibrary dylib) {
    final sodiumPtr = sodiumffi.SodiumPointer<Uint8>.alloc(
      sodiumffi.LibSodiumFFI(dylib),
      count: rawBytes.length,
    );

    sodiumPtr.fill(rawBytes);
    return SecureKeyFFI(sodiumPtr);
  }
}
```

I dont know if that's a efficient way to fill the memory with the raw bytes but seems to work. For your question, I think the most that making factory constructors to `SecureKey` would be a nicer approach, but I don't know it would affect the security internals of this implementation.
Anyways, great work on making this library, I was just needing a sodium wrapper and was not willing to make it by my own.

**Comment by Skycoder42** [comment]
You are actually quite on point with your implementation, it's basically the same thing the SecureKey classes do internally.
I decided to add factory constructors, and I think I like the outcome. Thanks for your input!

I will close this now as the original problem was solved. If you have any other feedback, feel free to create a new one. :)
