### ISSUE TITLE
Regenerate Sign KeyPair

### ISSUE THREAD

**Issue by SebastianKlaiber** [Skycoder42/libsodium_dart_bindings#10]
Hello, 
 
I am currently using the package for a 3D-Secure procedure. For this reason, I need to generate the SecureKey once for the lifetime of the app and then store it in the secure storage to release payments via the generated public key. 

My current procedure is to create a random string as a seed to create a keyPair. Is there a better way to do this? 

```dart
final seed = SecureKey.fromList(
  _sodium,
  Uint8List.fromList(data.codeUnits),
);

final keyPair = _sign.seedKeyPair(seed);

final secureKey = keyPair.secretKey;
```

Because `sign.keyPair()` always generates a complete new keyPair and for the detached method I need the secretKey object.

**Comment by Skycoder42** [comment]
Generally speaking, this is the correct way. However, there also exist methods to convert a private key back to a seed or a public key, so you could also use one of the following ways. Which one you choose is up to you, as they all do the same thing in the end.

Generate a key pair directly and store the seed:
```dart
// initial key generation
final key = _sign.keyPair();
final seed = _sign.skToSeed(key.secretKey);
// store seed

// load key from store
final seed = //...
final key = _sign.seedKeyPair(seed);
```

Generate a key pair directly and store the private key:
```dart
// initial key generation
final key = _sign.keyPair();
// store key.secretKey

// load key from store
final secretKey = //...
final publicKey = _sign.skToPk(secretKey);
```

**Important:** Both the `skToSeed` and the `skToPk` methods require you to use the sumo library on the web. For all other platforms, there are no restrictions.

You can also check the [Dart documentation](https://pub.dev/documentation/sodium/latest/sodium/Sign-class.html) and the [Official libsodium docs](https://libsodium.gitbook.io/doc/public-key_cryptography/public-key_signatures) for more details and examples.

**Comment by SebastianKlaiber** [comment]
Thank you. This solved my Problem.
