### ISSUE TITLE
Upgrade to latest freezed version

### ISSUE THREAD

**Issue by SebastianKlaiber** [Skycoder42/libsodium_dart_bindings#13]
Hi, 

Unfortunately, the package blocks me from updating Freezed and analyzer in my app and thus the latest language features of dart 2.17 cannot be used. 

Would it be possible to update the dependencies? I can also assist with this.

**Comment by Skycoder42** [comment]
Sorry for the late reply, I was not able to take care of this for a while. I will update the packages now.

**Comment by Skycoder42** [comment]
okay, this might take a few days, due to the addition of abi specific integers in dart ffi, I need to rewrite a bunch of low level code.

**Comment by Skycoder42** [comment]
Closed with [sodium 1.2.2](https://pub.dev/packages/sodium) and [sodium_libs 1.2.3](https://pub.dev/packages/sodium_libs)
