### ISSUE TITLE
How to set SecureKey manually?

### ISSUE THREAD

**Issue by tmp05** [Skycoder42/libsodium_dart_bindings#14]
I have my own secretKey (as Uint8List) - how can I use it in soda.crypto.box.easy?  I get an error  "Unhandled Exception: type 'Uint8List' is not a subtype of type 'SecureKey' in type cast" and I don't know how to convert Uint8List to SecureKey

**Comment by Skycoder42** [comment]
The library is fully documented. A short look at the [documentation](https://pub.dev/documentation/sodium/latest/sodium/SecureKey-class.html) will reveal that the SecureKey has a name constructor to do exactly that:

```dart
final key = SecureKey.fromList(sodium, myUint8ListKey);
```
