### ISSUE TITLE
Full build for Android version

### ISSUE THREAD

**Issue by falko17** [Skycoder42/libsodium_dart_bindings#15]
It seems that the dynamic libraries for Android (which are downloaded from this repository) don't contain certain methods which are necessary for certain applications. For example, in order to integrate [`libopaque`](https://github.com/stef/libopaque) into a Flutter app, it requires [Ristretto255](https://libsodium.gitbook.io/doc/advanced/point-arithmetic/ristretto) to be present in `libsodium`, i.e., it needs to be compiled with the `LIBSODIUM_FULL_BUILD` environment variable set.

The presence of a "full build" can be checked by using `nm -gD libsodium.so | grep ristretto` and seeing if any such symbols are present.
Would it be possible to integrate these full builds for Android into `sodium_libs`, instead of using minimal builds?

**Comment by Skycoder42** [comment]
Sure, I think that should be possible. The Android binaries are built in https://github.com/Skycoder42/libsodium_dart_bindings/blob/main/.github/workflows/android_libsodium.yaml. If you want, you can create a PR for that, otherwise I will try it myself as soon as I find the time.
