### ISSUE TITLE
Cannot read properties of undefined (reading 'then')

### ISSUE THREAD

**Issue by YannMarti** [Skycoder42/libsodium_dart_bindings#16]
Hi
When i try to initialize a sodium object (final sodium = await SodiumInit.init();) i get the error mentioned in the title. I tried it out with the provided example and get the same error.
What am i doing wrong?

**Comment by Skycoder42** [comment]
I cannot say anything without any more details. Please provide the following details:
1. Are you using flutter or a pure dart project
2. If using flutter, which platform(s) does that error happen on
3. If you can, please surround the init call with a try/catch to obtain the full stacktrace

**Comment by Skycoder42** [comment]
Without any further information, I sadly cannot help you
