### ISSUE TITLE
Speed of sodium.crypto.secretBox.easy() etc...

### ISSUE THREAD

**Issue by hootyjeremy** [Skycoder42/libsodium_dart_bindings#19]
Hello. I am trying this library after trying other crypto libraries and I heard that using libsodium native libraries would be faster than dart software implementations like PointyCastle. But I believe I'm getting the same speeds with this library and wanted to check whether I was doing something wrong or not. I am just creating a 100mb Uint8List and encrypting it and it is taking about 12 seconds with `sodium.crypto.secretBox.easy()` and `sodium.crypto.aead.encrypt()`. I have a gist of my sample code...

https://gist.github.com/hootyjeremy/54f43cb5c5886999a7fa255c13be10f9

Am I running these correctly? Are these two methods using the libsodium.dll native C code? Could you confirm if you're getting similar speeds (I know it will vary by machine) for these 100mb arrays? I was hoping to have them encrypt 100mb within 1 second which is what other software that encrypts with Chacha or AES will do.

**Comment by Skycoder42** [comment]
Hi. So I ran your gist on my local machine and got other results. On my machine, it takes about 5 seconds to encrypt the data with secretBox or aead. However, I also ran a more detailed benchmark, checking where this time comes from. Here are the results:

```
Beginning sodium.crypto.secretBox.easy() ...
> validation: 0:00:00.000316
> copy data to native: 0:00:04.989121
> encryption: 0:00:00.076314
> copy data to dart: 0:00:00.068359
duration for sodium.crypto.secretBox.easy:  0:00:05.140866
```

So as you can see, the encryption only takes 70 milliseconds. However, the step that copies the dart bytes array to native C takes up ca. 97% of the execution time!

The weird part here is, that the same number of bytes are copied from dart -> native as are copied back! So obviously, the native -> dart does something optimized, which does not happen the other way around.

I will investigate this and try to find out, why there is such a big difference.

**Comment by Skycoder42** [comment]
Okay, I already located the issue: I was accidentally iteration over the data array in dart as part of the copy process. I change the code to only use the built-it copy mechanisms of dart (which are optimized to use memcpy if possible) and now the times are much better:

```
--------------------------------------------
Beginning sodium.crypto.secretBox.easy() ...
duration for sodium.crypto.secretBox.easy:  0:00:00.192984
------------------------------------------
Beginning sodium.crypto.aead.encrypt() ...
duration for sodium.crypto.aead.encrypt:  0:00:00.247270
done
```

I will release a hotfix update asap, so you can test if this improves benchmarks for you as well.

**Comment by hootyjeremy** [comment]
Wow! Thanks a lot. I will look forward to the update.

**Comment by hootyjeremy** [comment]
I just tested 1.2.5 and it's finishing in ~0:00:00.186893 for encrypt and decrypt. Thanks for looking into this! Great work.
