### ISSUE TITLE
Can't generate keys on Android

### ISSUE THREAD

**Issue by cremfert** [Skycoder42/libsodium_dart_bindings#7]
I try to generate a secure key by using:
`await sodium.crypto.secretBox.keygen();` in Flutter (using `sodium_libs: ^1.1.1`).
This works fine on iOS, but fails with an error on Android:
`RangeError (RangeError (count): Invalid value: Not greater than or equal to 0: -5365866809427754976)`

How can I fix this?

Thanks a lot!

**Comment by Skycoder42** [comment]
Interesting. I have an idea where this could come from, but am not quite sure yet. Could you give me a stack trace? Specifically the parts regarding libsodium are important for me.

**Comment by Skycoder42** [comment]
Could you please add the following to your code, right before the `EncryptionV2Service.generateKey` method and send me the result? I cannot test on Android myself for the next few days, so that would help me working on this earlier.

**Comment by Skycoder42** [comment]
Also, which Android version and Architecture are you testing on

**Comment by Skycoder42** [comment]
I cannot reproduce your issue on my arm x64 device. I think I need more details about the exact device you are testing on

**Comment by Skycoder42** [comment]
I can confirm this happening and I do know why. The native C-Bindings for libsodium have been generated on a x86 machine, with size_t beeing resolved to UInt64. This of course does not work on a 32 bit system. For know, the easiest way around this is to create yourself a 64 bit emulator.

Regarding deployment to actuald devices, arm64 and intel x64 devices are fine, but older armv7 devices would not work. I will try to find a way around this issue

**Comment by Skycoder42** [comment]
I was able to confirm this. When I replace the "size_t" typedef in the generated bindings with "Uint32", the library works! Know I need to find a way to get the correct bindings based on architecture (which is not as easy as it sounds, as dart typically does not provide this information)

**Comment by Skycoder42** [comment]
Okay so I manage to get it to work by enforcing "size_t" to be interpreted as "IntPtr" - this works in regards of sizing, as for all supported system IntPtr has the same size as size_t, however, this messes up signed-ness, as IntPtr is signed, while size_t is not. I fixed things up so all test should succeed, but I have to walk through the whole library again to ensure all sizes are correctly interpreted. 

However, the current status should already be good enough to test out if it works for you as well, so if you have the time, please check out the latest master of `sodium` and overwrite it in your pubspec.

**Comment by cremfert** [comment]
Thanks a lot for your effort and your work - I really appreciate your help! I will have a chance to test next week and will provide feedback.

**Comment by Skycoder42** [comment]
I assume everything worked? If not, please reopen

**Comment by JustADevGuy** [comment]
Sorry, forgot to answer - yes, everything works! Thanks for your effort. I was just curious, if you also implemented the helper methods for conversion, like bin2hex and hex2bin etc.?

**Comment by cremfert** [comment]
Sorry, forgot to answer - yes, everything works! Thanks for your effort. I was just curious, if you also implemented the helper methods for conversion, like bin2hex and hex2bin etc.?

**Comment by Skycoder42** [comment]
No, i did not implement the helpers, as dart itself provides similar functions, which are much more efficient as no conversion between dart and the native code is required
